import "./reset.css";
import "./globals.css";
import type { Metadata } from "next";
import { noto_sans, poppins } from "./fonts";
import Header from "@/layout/header/Header";
import Providers from "@/context/providers";

export const metadata: Metadata = {
  title: "KaveHome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${noto_sans.variable} ${poppins.variable}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
